@auth = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjFhYTkyODYwMTZjNzE0YTgzOTE0OSIsInJ1bGVzIjpbInVzZXIiXSwiaWF0IjoxNjYzNzE3MjcwLCJleHAiOjE2NjM4MDM2NzB9.fhJLHjj8ObqxF2h1tAhgAF4SCvzFZzaPuvPOTrx7Nro
@host = http://localhost
@port = 3001
@endpoint = /users

@url = {{host}}:{{port}}{{endpoint}}

### Post /users CREATE Criação de Usuário.
POST http://localhost:3001/users HTTP/1.1
content-type: application/json

{
    "name":"Marcela", 
    "nickName":"marce", 
    "email":"mama@mail.com", 
    "password":"123456789"
}
### GET /users READ Lista todos os Usuários.
GET {{url}} HTTP/1.1
Authorization: Bearer {{auth}}



### GET /users/:id READ Only Lista um Usuário por ID.
GET {{url}}/6321aa9286016c714a839149 HTTP/1.1




### PUT /users/:id UPDATE Only por ID.
PUT {{url}}/63236ee9419d5acf24acf56e HTTP/1.1  
content-type: application/json

{   
    "name":"Monique Geovana Marques de Albuquerque", 
    "nickName":"nini", 
    "email":"nini@mail.com", 
    "password":"123456789",
    "urlProfileImg":"https://i.pravatar.cc/150?img=26"

}


### DELETE /users/:id DELETE Only por ID.
DELETE {{url}}/63236ff3419d5acf24acf578 HTTP/1.1  


### POST /users/auth AUTH Autentica o Usuário.
POST {{url}}/auth 
content-type: application/json

{
    "email":"lu@mail.com", 
    "password":"12345678"
}
###
